// <auto-generated />
using System;
using CustomSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomSync.Data.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260828122635_AddMediaUploadedByDevice")]
    partial class AddMediaUploadedByDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomSync.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("actor_device_id");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorDeviceId")
                        .HasDatabaseName("idx_audit_actor");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<long>("LastCursor")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cursor");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("DeviceId")
                        .HasName("pk_devices");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.EnrollmentCodeEntity", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantsRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grants_role");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UsedBy")
                        .HasColumnType("text")
                        .HasColumnName("used_by");

                    b.HasKey("CodeHash")
                        .HasName("pk_enrollment_codes");

                    b.ToTable("enrollment_codes", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.KeyWrapEntity", b =>
                {
                    b.Property<string>("WrapId")
                        .HasColumnType("text")
                        .HasColumnName("wrap_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasColumnName("iterations");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<string>("WrapType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wrap_type");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.HasKey("WrapId")
                        .HasName("pk_key_wraps");

                    b.ToTable("key_wraps", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.MediaBlobEntity", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_device_id");

                    b.HasKey("Hash")
                        .HasName("pk_media_blobs");

                    b.ToTable("media_blobs", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("AccountHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_hash");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("MsgId")
                        .HasColumnType("bigint")
                        .HasColumnName("msg_id");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_at");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("bigint")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("integer")
                        .HasColumnName("payload_size");

                    b.Property<string>("PeerHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peer_hash");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("TargetRecordId")
                        .HasColumnType("text")
                        .HasColumnName("target_record_id");

                    b.HasKey("RecordId")
                        .HasName("pk_records");

                    b.HasIndex("Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_records_seq");

                    b.HasIndex("TargetRecordId")
                        .HasDatabaseName("idx_records_tombstone_target")
                        .HasFilter("target_record_id IS NOT NULL");

                    b.HasIndex("OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_occur");

                    b.HasIndex("AccountHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_account");

                    b.HasIndex("Kind", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_kind");

                    b.HasIndex("PeerHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_peer");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordMediaEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("RecordId", "Hash")
                        .HasName("pk_record_media");

                    b.ToTable("record_media", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ServerSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_type");

                    b.HasKey("Key")
                        .HasName("pk_server_settings");

                    b.ToTable("server_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
