// <auto-generated />
using System;
using CustomSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomSync.Data.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260826113207_AddAccountHash")]
    partial class AddAccountHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomSync.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastCursor")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.EnrollmentCodeEntity", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedBy")
                        .HasColumnType("text");

                    b.HasKey("CodeHash");

                    b.ToTable("enrollment_codes", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.KeyWrapEntity", b =>
                {
                    b.Property<string>("WrapId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("WrapType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("WrapId");

                    b.ToTable("key_wraps", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.MediaBlobEntity", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Hash");

                    b.ToTable("media_blobs", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<string>("AccountHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MsgId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("integer");

                    b.Property<string>("PeerHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasKey("RecordId");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_occur");

                    b.HasIndex("AccountHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_account");

                    b.HasIndex("Kind", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_kind");

                    b.HasIndex("PeerHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_peer");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordMediaEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.HasKey("RecordId", "Hash");

                    b.ToTable("record_media", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ServerSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("server_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
