// <auto-generated />
using System;
using CustomSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomSync.Data.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260913182035_AddArchiveRunsAndOrphanedMedia")]
    partial class AddArchiveRunsAndOrphanedMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomSync.Data.Entities.ArchiveRunEntity", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<string>("ArchiveLocation")
                        .HasColumnType("text")
                        .HasColumnName("archive_location");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_count");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("FreedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("freed_bytes");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<int>("MissingMedia")
                        .HasColumnType("integer")
                        .HasColumnName("missing_media");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.HasKey("RunId")
                        .HasName("pk_archive_runs");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_archive_runs_policy_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_archive_runs_started_at");

                    b.ToTable("archive_runs", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("actor_device_id");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorDeviceId")
                        .HasDatabaseName("idx_audit_actor");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_log_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<long>("LastCursor")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cursor");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("DeviceId")
                        .HasName("pk_devices");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.EnrollmentCodeEntity", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantsRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grants_role");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UsedBy")
                        .HasColumnType("text")
                        .HasColumnName("used_by");

                    b.HasKey("CodeHash")
                        .HasName("pk_enrollment_codes");

                    b.ToTable("enrollment_codes", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.KeyWrapEntity", b =>
                {
                    b.Property<string>("WrapId")
                        .HasColumnType("text")
                        .HasColumnName("wrap_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasColumnName("iterations");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<string>("WrapType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wrap_type");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.HasKey("WrapId")
                        .HasName("pk_key_wraps");

                    b.ToTable("key_wraps", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.MediaBlobEntity", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orphaned_at");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_device_id");

                    b.HasKey("Hash")
                        .HasName("pk_media_blobs");

                    b.HasIndex("OrphanedAt")
                        .HasDatabaseName("ix_media_blobs_orphaned_at")
                        .HasFilter("orphaned_at IS NOT NULL");

                    b.ToTable("media_blobs", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("AccountHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_hash");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("MsgId")
                        .HasColumnType("bigint")
                        .HasColumnName("msg_id");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_at");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("bigint")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadSize")
                        .HasColumnType("integer")
                        .HasColumnName("payload_size");

                    b.Property<string>("PeerHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peer_hash");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("TargetRecordId")
                        .HasColumnType("text")
                        .HasColumnName("target_record_id");

                    b.HasKey("RecordId")
                        .HasName("pk_records");

                    b.HasIndex("Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_records_seq");

                    b.HasIndex("TargetRecordId")
                        .HasDatabaseName("idx_records_tombstone_target")
                        .HasFilter("target_record_id IS NOT NULL");

                    b.HasIndex("OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_occur");

                    b.HasIndex("AccountHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_account");

                    b.HasIndex("Kind", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_kind");

                    b.HasIndex("PeerHash", "OccurredAt", "Seq")
                        .HasDatabaseName("idx_records_peer");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RecordMediaEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("RecordId", "Hash")
                        .HasName("pk_record_media");

                    b.ToTable("record_media", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ReleaseEntity", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("text")
                        .HasColumnName("release_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("ReleaseId")
                        .HasName("pk_releases");

                    b.HasIndex("Platform", "Version", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_platform_version_channel");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ReleaseMirrorEntity", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("text")
                        .HasColumnName("release_id");

                    b.Property<string>("Mirror")
                        .HasColumnType("text")
                        .HasColumnName("mirror");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("ReleaseId", "Mirror")
                        .HasName("pk_release_mirrors");

                    b.ToTable("release_mirrors", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.RetentionPolicyEntity", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<bool>("MediaOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("media_only");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OlderThanDays")
                        .HasColumnType("integer")
                        .HasColumnName("older_than_days");

                    b.Property<string>("PeerHash")
                        .HasColumnType("text")
                        .HasColumnName("peer_hash");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId")
                        .HasName("pk_retention_policies");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_retention_policies_priority");

                    b.ToTable("retention_policies", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ServerSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_type");

                    b.HasKey("Key")
                        .HasName("pk_server_settings");

                    b.ToTable("server_settings", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.UploadSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("Received")
                        .HasColumnType("bigint")
                        .HasColumnName("received");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("release_id");

                    b.Property<string>("TempPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("temp_path");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size");

                    b.HasKey("SessionId")
                        .HasName("pk_upload_sessions");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_upload_sessions_release_id");

                    b.ToTable("upload_sessions", (string)null);
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ReleaseMirrorEntity", b =>
                {
                    b.HasOne("CustomSync.Data.Entities.ReleaseEntity", "Release")
                        .WithMany("Mirrors")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_mirrors_releases_release_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("CustomSync.Data.Entities.ReleaseEntity", b =>
                {
                    b.Navigation("Mirrors");
                });
#pragma warning restore 612, 618
        }
    }
}
